### ISSUE TITLE
Serious Performance issues

### ISSUE THREAD

**Issue by aproposnix** [SkyzohKey/M-Droid#19]
On a new mobile (completely new install) running Android 7, the performance of mDroid is just terrible. Some things to improve the performance could be: 

1. When a user opens the app, he/she should be taken directly to the list of apps (from the previous sync). 
2. Need to have background syncing (like the newer version of F-Droid) 
3. Do not enable all of the repos from the start.  This should be an opt-in (with a proper explanation of each of the repos - are they trustworthy?)

I really like where you are going with this, I just hope you can improve the performance. Until then, I'll have to keep using F-Droid. 

Phone: Huawei P10 Lite
Android: 7.0

**Comment by SkyzohKey** [comment]
I also noticed some issues with performances. Let me reply to your bullets.

1. That's the case, the loading is due to cache because the app has to read multiple files for each repositories. F-Droid one contains almost 1400 apps, + F-Droid Archives which is 1900 apps fat. I'm looking for a way to improve this (ie. stream read the file, but then parsing it as JSON would error, I've to rethink this).
2. Background sync is definitly planed ;)
3. This is also planed. Only the F-Droid main repo' will be enable at start, then you'll be able to enable the other repositories. They'll still be listed but not enabled.

Thanks for the kind words, I appreciate feedbacks!
