### ISSUE TITLE
Runtime permissions

### ISSUE THREAD

**Issue by Madis0** [SkyzohKey/M-Droid#3]
Why would you build a new app targeting Lollipop? I don't understand the need for phone permission either.

**Comment by SkyzohKey** [comment]
Because that's what older React Native can support.  
Speaking about permissions, they are used the following way:

- **WRITE_EXTERNAL_STORAGE** : Used to read/write repos cache, also used to download & store the APK of the apps you installs.
- **INTERNET** : Used to... Everything network related (fetching repos, downloading apps, fetch apps' icons/featureGraphic, etc)
- **ACCESS_NETWORK_STATE** : Used to detect when internet goes down/up and updating the UI in consequences.

**Comment by Madis0** [comment]
The network state makes sense, but I see a phone state, what is that for?

**Comment by SkyzohKey** [comment]
It's being added by React I dunno why, will be removed in the next release.
